//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Blazor.Import.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Blazor.Import.Resources.ImportResources.de", typeof(ImportResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei auswählen.
        /// </summary>
        internal static string Button_SelectFile {
            get {
                return ResourceManager.GetString("Button.SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import starten.
        /// </summary>
        internal static string Button_StartImport {
            get {
                return ResourceManager.GetString("Button.StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeiner Fehler.
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler in Zeile {0} .
        /// </summary>
        internal static string Error_Row {
            get {
                return ResourceManager.GetString("Error.Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlermeldungen.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits vorhandene Datensätze.
        /// </summary>
        internal static string ExistingEntries {
            get {
                return ResourceManager.GetString("ExistingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignorieren.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importtyp.
        /// </summary>
        internal static string ImportType {
            get {
                return ResourceManager.GetString("ImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde noch keine Importtyp ausgewählt.
        /// </summary>
        internal static string NoImportType {
            get {
                return ResourceManager.GetString("NoImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde noch keine Datei ausgewählt.
        /// </summary>
        internal static string NoSelectedFile {
            get {
                return ResourceManager.GetString("NoSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensätze erstellt.
        /// </summary>
        internal static string RecordsCreated {
            get {
                return ResourceManager.GetString("RecordsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensätze ignoriert.
        /// </summary>
        internal static string RecordsIgnored {
            get {
                return ResourceManager.GetString("RecordsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensätze gesamt.
        /// </summary>
        internal static string RecordsProcessed {
            get {
                return ResourceManager.GetString("RecordsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensätze aktualisiert.
        /// </summary>
        internal static string RecordsUpdated {
            get {
                return ResourceManager.GetString("RecordsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Import wurde mit Fehlern abgebrochen. Es wurden keine Datensätze importiert..
        /// </summary>
        internal static string Result_Error {
            get {
                return ResourceManager.GetString("Result.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Datensätze importiert..
        /// </summary>
        internal static string Result_Info {
            get {
                return ResourceManager.GetString("Result.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Import wurde erfolgreich abgeschlossen..
        /// </summary>
        internal static string Result_Success {
            get {
                return ResourceManager.GetString("Result.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten nicht alle Datensätze erfolgreich importiert werden..
        /// </summary>
        internal static string Result_Warning {
            get {
                return ResourceManager.GetString("Result.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammenfassung.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktualisieren.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
