//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Blazor.Theme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThemeResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemeResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Blazor.Theme.Resources.ThemeResources.de", typeof(ThemeResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftgröße.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe des Textes in der Benutzeroberfläche (z.B. 16px oder 1rem)..
        /// </summary>
        internal static string FontSize_Description {
            get {
                return ResourceManager.GetString("FontSize.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Schriftgröße. Erlaubt sind Werte wie z. B. 16px oder 1rem..
        /// </summary>
        internal static string FontSize_Invalid {
            get {
                return ResourceManager.GetString("FontSize.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primärfarbe.
        /// </summary>
        internal static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfarbe für Schaltflächen, Links und Akzente..
        /// </summary>
        internal static string PrimaryColor_Description {
            get {
                return ResourceManager.GetString("PrimaryColor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekundärfarbe.
        /// </summary>
        internal static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergänzende Farbe für UI-Elemente und Hintergründe..
        /// </summary>
        internal static string SecondaryColor_Description {
            get {
                return ResourceManager.GetString("SecondaryColor.Description", resourceCulture);
            }
        }
    }
}
