//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Blazor.Audit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Blazor.Audit.Resources.AuditResources.de", typeof(AuditResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat den Datensatz erstellt.
        /// </summary>
        internal static string action_created {
            get {
                return ResourceManager.GetString("action.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat den Datensatz gelöscht.
        /// </summary>
        internal static string action_deleted {
            get {
                return ResourceManager.GetString("action.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat eine unbekannte Änderung durchgeführt.
        /// </summary>
        internal static string action_unknown {
            get {
                return ResourceManager.GetString("action.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat den Datensatz geändert.
        /// </summary>
        internal static string action_updated {
            get {
                return ResourceManager.GetString("action.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat {1} geändert.
        /// </summary>
        internal static string action_updated_fields {
            get {
                return ResourceManager.GetString("action.updated-fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat {1} und {2} weitere geändert.
        /// </summary>
        internal static string action_updated_remaining {
            get {
                return ResourceManager.GetString("action.updated-remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details ausblenden.
        /// </summary>
        internal static string hide_details {
            get {
                return ResourceManager.GetString("hide-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Wert.
        /// </summary>
        internal static string new_value {
            get {
                return ResourceManager.GetString("new-value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neueste zuerst.
        /// </summary>
        internal static string newest_first {
            get {
                return ResourceManager.GetString("newest-first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter Wert.
        /// </summary>
        internal static string old_value {
            get {
                return ResourceManager.GetString("old-value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Älteste zuerst.
        /// </summary>
        internal static string oldest_first {
            get {
                return ResourceManager.GetString("oldest-first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details anzeigen.
        /// </summary>
        internal static string show_details {
            get {
                return ResourceManager.GetString("show-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am {0} um {1} Uhr.
        /// </summary>
        internal static string timestamp {
            get {
                return ResourceManager.GetString("timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Änderungen.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
