//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Blazor.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Blazor.Account.Resources.AccountResources.de", typeof(AccountResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort für Benutzer &apos;{0}&apos; wurde erfolgreich geändert..
        /// </summary>
        internal static string ChangePasswordDialog_SuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePasswordDialog.SuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern für &apos;{0}&apos;.
        /// </summary>
        internal static string ChangePasswordDialog_Title {
            get {
                return ResourceManager.GetString("ChangePasswordDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer sperren.
        /// </summary>
        internal static string LockUser {
            get {
                return ResourceManager.GetString("LockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Benutzer &apos;{0}&apos; wirklich gesperrt werden?.
        /// </summary>
        internal static string LockUserDialog_ContentLock {
            get {
                return ResourceManager.GetString("LockUserDialog.ContentLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Benutzer &apos;{0}&apos; wirklich entsperrt werden?.
        /// </summary>
        internal static string LockUserDialog_ContentUnlock {
            get {
                return ResourceManager.GetString("LockUserDialog.ContentUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer &apos;{0}&apos; wurde erfolgreich gesperrt..
        /// </summary>
        internal static string LockUserDialog_SuccessfullyLocked {
            get {
                return ResourceManager.GetString("LockUserDialog.SuccessfullyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer &apos;{0}&apos; wurde erfolgreich entsperrt..
        /// </summary>
        internal static string LockUserDialog_SuccessfullyUnlocked {
            get {
                return ResourceManager.GetString("LockUserDialog.SuccessfullyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer entsperren.
        /// </summary>
        internal static string UnlockUser {
            get {
                return ResourceManager.GetString("UnlockUser", resourceCulture);
            }
        }
    }
}
